    // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VmixData.Models;

public partial class Match
{
    public int Id { get; set; }

    public string MatchName { get; set; }

    public int MatchId { get; set; }

    public int TournamentId { get; set; }

    public int MatchDayId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int StageId { get; set; }
}