// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VmixData.Models;

public partial class Mvpmodel
{
    public string PlayerUid { get; set; }

    public int TeamId { get; set; }

    public int StageId { get; set; }

    public int TournamentId { get; set; }

    public string Name { get; set; }

    public int? Damage { get; set; }

    public int? Eliminations { get; set; }

    public Double? SurvivalTime { get; set; }
}