// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VmixData.Models;

public partial class PlayerStat
{
    public int PlayerStatId { get; set; }

    public int MatchId { get; set; }

    public long PlayerUId { get; set; }

    public string PlayerOpenId { get; set; }

    public string PlayerName { get; set; }

    public string PicUrl { get; set; }

    public bool? ShowPicUrl { get; set; }

    public int TeamId { get; set; }

    public string Character { get; set; }

    public bool? IsFiring { get; set; }

    public int? PosX { get; set; }

    public int? PosY { get; set; }

    public int? PosZ { get; set; }

    public int? Health { get; set; }

    public int? HealthMax { get; set; }

    public int? LiveState { get; set; }

    public int? KillNum { get; set; }

    public int? KillNumBeforeDie { get; set; }

    public long? PlayerKey { get; set; }

    public int? GotAirdropNum { get; set; }

    public int? MaxKillDistance { get; set; }

    public int? Damage { get; set; }

    public int? InDamage { get; set; }

    public int? Heal { get; set; }

    public int? HeadshotNum { get; set; }

    public int? KillNumInVehicle { get; set; }

    public int? SurvivalTime { get; set; }

    public int? DriveDistance { get; set; }

    public int? MarchDistance { get; set; }

    public int? Assists { get; set; }

    public int? KillNumByGrenade { get; set; }

    public int? Rank { get; set; }

    public bool? IsOutsideBlueCircle { get; set; }

    public int? OutsideBlueCircleTime { get; set; }

    public int? UseFragGrenadeNum { get; set; }

    public int? UseSmokeGrenadeNum { get; set; }

    public int? HealTeammateNum { get; set; }

    public int? CurWeaponId { get; set; }

    public int? Knockouts { get; set; }

    public int? RescueTimes { get; set; }

    public int? StageId { get; set; }
}