// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VmixData.Models;

public partial class SportTeam
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public byte[] Icon { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}