// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VmixData.Models;

public partial class TeamPoint
{
    public int TeamPointId { get; set; }

    public int MatchId { get; set; }

    public int DayId { get; set; }

    public int StageId { get; set; }

    public int TeamId { get; set; }

    public int TeamName { get; set; }
    public int WWCD { get; set; }

    public int PlacementPoints { get; set; }

    public int KillPoints { get; set; }

    public int TotalPoints { get; set; }
}