// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VmixData.Models;

public partial class Team
{
    public int Id { get; set; }

    public string TeamId { get; set; }

    public string TeamName { get; set; }

    public int? TournamentId { get; set; }

    public int? StageId { get; set; }

    public virtual Tournament Tournament { get; set; }
}