// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pubg_Ranking_System.Models;

public partial class Match
{
    public int MatchId { get; set; }

    public int TournamentId { get; set; }

    public int MatchDayId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int? StageId { get; set; }

    public virtual ICollection<PlayerStat> PlayerStats { get; set; } = new List<PlayerStat>();

    public virtual ICollection<TeamPoint> TeamPoints { get; set; } = new List<TeamPoint>();

    public virtual Tournament Tournament { get; set; }
}