// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pubg_Ranking_System.Models;

public partial class Player
{
    public int Id { get; set; }

    public string PlayerGameName { get; set; }

    public string PlayerDisplayName { get; set; }
}