// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pubg_Ranking_System.Models;

public partial class TeamsStage
{
    public int TeamStageDayId { get; set; }

    public int TournamentId { get; set; }

    public int StageId { get; set; }

    public int DayNumber { get; set; }

    public int TeamId { get; set; }

    public string TeamName { get; set; }

    public virtual Stage Stage { get; set; }

    public virtual Tournament Tournament { get; set; }
}