// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pubg_Ranking_System.Models;

public partial class TeamPoint
{
    public int TeamPointId { get; set; }

    public int MatchId { get; set; }

    public int TeamId { get; set; }

    public int PlacementPoints { get; set; }

    public int KillPoints { get; set; }

    public int TotalPoints { get; set; }

    public virtual Match Match { get; set; }
}