using Pubg_Ranking_System.Tenancy;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System.Text.Json;
using VmixData.Models.MatchModels;
using VmixGraphicsBusiness;
using VmixGraphicsBusiness.LiveMatch;
using VmixGraphicsBusiness.PostMatchStats;
using VmixGraphicsBusiness.Utils;

namespace Pubg_Ranking_System
{
    /// <summary>
    /// One pcob poll tick, as pushed by VmixIngestAgent (the small program that runs on the
    /// customer's PC next to pcob) instead of this application polling pcob itself.
    /// PlayerListJson/TeamInfoJson are the exact raw response bodies pcob's own
    /// gettotalplayerlist / getteaminfolist endpoints return - deserialized here with the same
    /// models GetLiveData.FetchAndPostData already uses, so there is exactly one place that
    /// understands the pcob response shape, not two.
    ///
    /// SessionId/Seq are the ordering pair. Seq counts ticks from 1 within one agent session;
    /// SessionId is regenerated by the agent at the start of every match and on restart, which is
    /// what lets Seq legitimately go back to 1 without the server reading that as a flood of
    /// stale ticks. Both are optional so an older agent build that doesn't send them keeps
    /// working - such ticks skip the ordering guard entirely and behave exactly as before.
    /// </summary>
    public record IngestTickRequest(
        bool IsInGame,
        string? PlayerListJson,
        string? TeamInfoJson,
        string? SessionId = null,
        long? Seq = null,
        string? KillInfoJson = null);

    /// <summary>
    /// Receives live match data from VmixIngestAgent when this application isn't running on the
    /// same machine/LAN segment as pcob (the normal production topology once the graphics
    /// pipeline is hosted centrally instead of on each event's local PC) - the other half of the
    /// "collector on the customer PC, processing centrally" split the user asked for.
    ///
    /// This is a second way to feed the exact same pipeline GetLiveData.FetchAndPostData already
    /// drives (LiveStatsBusiness.CreateDynamicLiveStats -> MatchStateStore.PublishLiveTeams ->
    /// SignalR -> the React dashboard/overlay), not a parallel one - see StartMatchRequest.Mode in
    /// MatchControlApi.cs for how an operator picks which source feeds a given match.
    /// </summary>
    public static class IngestApi
    {
        public static void MapIngestEndpoints(this WebApplication app, IServiceProvider rootProvider, IConfiguration configuration, IngestCoordinator ingestCoordinator)
        {
            app.MapPost("/api/ingest/tick", async (HttpRequest httpRequest, IngestTickRequest tick) =>
            {
                // Auth now happens in the endpoint filter (RequireAgentKey, below), which accepts
                // either this tournament's own generated agent key or the legacy shared
                // Agent:IngestKey - so agents already in the field keep working unchanged while
                // new ones get a per-tournament credential that can be revoked on its own.
                //
                // The filter has also already resolved WHICH tournament this agent feeds, so from
                // here on every piece of state comes from that tenant's scope rather than from the
                // process-wide singletons. That is the whole of multi-tenant ingest: one agent, one
                // tournament, no shared coordinator for two events to collide in.
                var tenant = httpRequest.HttpContext.GetTenant();
                var tenantScope = tenant.Scope!;
                var coordinator = tenantScope.Ingest;
                var agentVersion = httpRequest.Headers["X-Agent-Version"].ToString();
                var logs = httpRequest.HttpContext.RequestServices.GetRequiredService<TenantScopeManager>();

                var match = coordinator.CurrentMatch;
                if (match is null)
                {
                    return Results.Json(new { ok = false, error = "No active match - call POST /api/match/start with mode=\"agent\" first." }, statusCode: StatusCodes.Status409Conflict);
                }

                // Ordering guard, first half. The agent sends ticks in order, but they do not
                // necessarily arrive in order: one slow request (or one the agent already gave up
                // waiting on at HttpTimeoutSeconds, while this server kept processing it) can be
                // overtaken by the tick behind it. Processing the older one afterwards would
                // overwrite fresher stats with staler ones and make the overlay jump backwards.
                var sequenced = !string.IsNullOrWhiteSpace(tick.SessionId) && tick.Seq.HasValue;
                if (sequenced && !coordinator.TryAdmitTick(tick.SessionId!, tick.Seq!.Value, out var currentSeq))
                {
                    // 200, not 4xx: the agent did nothing wrong and must not retry - this tick is
                    // simply older than one already applied, and the right move is to forget it
                    // and let the next poll carry the current state.
                    tenantScope.Agent.RecordDroppedTick();
                    return Results.Ok(new
                    {
                        ok = true,
                        applied = false,
                        reason = "stale",
                        seq = tick.Seq!.Value,
                        currentSeq,
                    });
                }

                if (!tick.IsInGame)
                {
                    // In-game -> not-in-game transition is the same "match just ended" signal
                    // GetLiveData.FetchAndPostData's own while(IsInGame) loop exiting represents -
                    // run the same post-match step it runs afterward, exactly once.
                    if (coordinator.WasInGame)
                    {
                        using var endScope = rootProvider.CreateScope();
                        var postMatchAtEnd = endScope.ServiceProvider.GetRequiredService<PostMatch>();
                        try
                        {
                            if (!string.IsNullOrWhiteSpace(tick.PlayerListJson) && !string.IsNullOrWhiteSpace(tick.TeamInfoJson))
                            {
                                var finalPlayers = JsonSerializer.Deserialize<LivePlayersList>(tick.PlayerListJson)!;
                                var finalTeams = JsonSerializer.Deserialize<TeamInfoList>(tick.TeamInfoJson)!;
                                await postMatchAtEnd.createPostMtachStats(finalPlayers, match, finalTeams);
                            }
                        }
                        catch (Exception ex)
                        {
                            // Post-match processing must never take the ingest endpoint down with
                            // it - same "log and move on" contract PostMatch.cs's own
                            // RunPostMatchStepAsync wrapper follows for its 7 steps.
                            Console.WriteLine($"Ingest end-of-match post-processing failed: {ex.Message}");
                        }
                        tenantScope.MatchState.PublishMatchStatus("");
                        coordinator.Clear();
                    }
                    return Results.Ok(new { ok = true, applied = true, matchEnded = coordinator.CurrentMatch is null });
                }

                if (string.IsNullOrWhiteSpace(tick.PlayerListJson) || string.IsNullOrWhiteSpace(tick.TeamInfoJson))
                {
                    return Results.Json(new { ok = false, error = "IsInGame=true ticks must include PlayerListJson and TeamInfoJson." }, statusCode: StatusCodes.Status400BadRequest);
                }

                using var scope = rootProvider.CreateScope();
                var liveStatsBusiness = scope.ServiceProvider.GetRequiredService<LiveStatsBusiness>();
                var matchState = tenantScope.MatchState;

                // Real per-elimination feed, agent-mode half. The tracker lives on the coordinator
                // so it spans ticks and clears with the match, exactly as GetLiveData's own
                // instance does for direct mode. One sample payload is logged per match so the
                // assumed getkillinfo field names (see KillInfo) can be confirmed for real.
                if (!string.IsNullOrWhiteSpace(tick.KillInfoJson) && coordinator.KillFeed.ShouldLogRawSample())
                {
                    Console.WriteLine($"[killfeed] first getkillinfo payload this match: {tick.KillInfoJson}");
                }
                foreach (var kill in coordinator.KillFeed.GetNewKills(tick.KillInfoJson))
                {
                    matchState.PublishKill(new LiveKillEvent(
                        kill.KillerName ?? "Unknown",
                        kill.VictimName ?? "an opponent",
                        kill.Distance,
                        KillFeedTracker.IsLongRange(kill)));
                }

                var published = true;
                try
                {
                    var rawPlayers = JsonSerializer.Deserialize<LivePlayersList>(tick.PlayerListJson)!;
                    var teamInfoList = JsonSerializer.Deserialize<TeamInfoList>(tick.TeamInfoJson)!;
                    var filteredPlayerInfo = LiveStatsBusiness.FilterPlayerInfo(rawPlayers);

                    var liveStatsResult = await liveStatsBusiness.CreateDynamicLiveStats(match, filteredPlayerInfo, teamInfoList, coordinator.TeamPoints ?? new List<LiveTeamPointStats>());
                    if (liveStatsResult is List<TeamLiveStats> teamLiveStatsList)
                    {
                        // Ordering guard, second half. Admission order is not completion order:
                        // ticks 5 and 6 can both be legitimately admitted and still finish out of
                        // order if 5's processing runs slower. Re-check right before the result
                        // goes on air, and throw it away if a newer tick beat it there.
                        if (!sequenced || coordinator.TryMarkPublished(tick.SessionId!, tick.Seq!.Value))
                        {
                            matchState.PublishLiveTeams(teamLiveStatsList);
                        }
                        else
                        {
                            published = false;
                        }
                    }
                }
                catch (Exception ex)
                {
                    // Previously this returned 400 and left no trace anywhere the operator would
                    // see. A tick that fails to process is exactly the kind of thing that shows up
                    // on air as a frozen leaderboard, so it gets logged against the tournament.
                    logs.Publish("Error", "ingest", "failed to process tick", tenantScope.TournamentId,
                        error: ex.ToString(),
                        properties: new Dictionary<string, string>
                        {
                            ["seq"] = tick.Seq?.ToString() ?? "-",
                            ["agentVersion"] = string.IsNullOrEmpty(agentVersion) ? "-" : agentVersion,
                            ["correlationId"] = tenant.CorrelationId,
                        });
                    tenantScope.Agent.RecordDroppedTick();
                    return Results.Json(new { ok = false, error = $"Failed to process tick: {ex.Message}" }, statusCode: StatusCodes.Status400BadRequest);
                }

                if (published)
                {
                    tenantScope.Agent.RecordAcceptedTick(agentVersion, tick.SessionId);
                }
                else
                {
                    tenantScope.Agent.RecordDroppedTick();
                }

                coordinator.WasInGame = true;
                return published
                    ? Results.Ok(new { ok = true, applied = true, seq = tick.Seq })
                    : Results.Ok(new { ok = true, applied = false, reason = "superseded", seq = tick.Seq, currentSeq = coordinator.PublishedSeq });
            }).RequireAgentKey();

            // Admin-only diagnostic (not used by /overlay or by VmixIngestAgent itself, which only
            // ever POSTs to /tick) - gated behind the dashboard key like every other admin action.
            app.MapGet("/api/ingest/status", (HttpRequest httpRequest) =>
            {
                // Scoped to the caller's tournament rather than to the one process-wide
                // coordinator, so two events on one host report their own numbers.
                var statusCoordinator = httpRequest.HttpContext.GetTenant().Scope?.Ingest ?? ingestCoordinator;
                var match = statusCoordinator.CurrentMatch;
                return Results.Json(new
                {
                    active = match is not null,
                    matchId = match?.MatchId,
                    wasInGame = statusCoordinator.WasInGame,
                    // Ordering diagnostics. publishedSeq trailing acceptedSeq slightly is normal;
                    // steadily climbing drop counts mean the agent-to-server link is reordering
                    // or retrying enough to be worth looking at.
                    sessionId = statusCoordinator.SessionId,
                    acceptedSeq = statusCoordinator.AcceptedSeq,
                    publishedSeq = statusCoordinator.PublishedSeq,
                    staleTicksDropped = statusCoordinator.StaleTicksDropped,
                    supersededTicksDropped = statusCoordinator.SupersededTicksDropped,
                });
            }).RequireDashboardKey();
        }
    }
}
